// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3oRI9hPSdP2yuDITQ7dvBriDy2yIB938',
    appId: '1:136982059550:web:bb1bf9bbe6fa95296a6c0f',
    messagingSenderId: '136982059550',
    projectId: 'crmproject-1523c',
    authDomain: 'crmproject-1523c.firebaseapp.com',
    storageBucket: 'crmproject-1523c.firebasestorage.app',
    measurementId: 'G-D9RJ41E3HN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDO7LXVvKjluZ59ODN_4UFWotgEx3oT4Bk',
    appId: '1:136982059550:android:823fd9e62c6c89ed6a6c0f',
    messagingSenderId: '136982059550',
    projectId: 'crmproject-1523c',
    storageBucket: 'crmproject-1523c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZJo7emQNWpWoFD7T0P_6HofcpbFrRz3I',
    appId: '1:136982059550:ios:df1838e3795cd40f6a6c0f',
    messagingSenderId: '136982059550',
    projectId: 'crmproject-1523c',
    storageBucket: 'crmproject-1523c.firebasestorage.app',
    iosBundleId: 'com.example.maitexaCrmFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZJo7emQNWpWoFD7T0P_6HofcpbFrRz3I',
    appId: '1:136982059550:ios:df1838e3795cd40f6a6c0f',
    messagingSenderId: '136982059550',
    projectId: 'crmproject-1523c',
    storageBucket: 'crmproject-1523c.firebasestorage.app',
    iosBundleId: 'com.example.maitexaCrmFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3oRI9hPSdP2yuDITQ7dvBriDy2yIB938',
    appId: '1:136982059550:web:194c31dc54a7ae466a6c0f',
    messagingSenderId: '136982059550',
    projectId: 'crmproject-1523c',
    authDomain: 'crmproject-1523c.firebaseapp.com',
    storageBucket: 'crmproject-1523c.firebasestorage.app',
    measurementId: 'G-GJLYNLBR2L',
  );
}
